version: 2

models:
  - name: omni_swap_rate
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [END_MONTH]
    columns:
      - name: END_MONTH
        data_type: varchar
        tests:
          - unique
          - not_null
      - name: SWAP_RATE
        data_type: varchar
