version: 2

models:
  - name: stg_swap_rate
    description: "Upstream staging table for swap rates."
    config:
      materialized: table
      contract:
        enforced: true
    columns:
      - name: END_MONTH
        description: "{{ doc('col_end_month') }}"
        data_type: varchar
      - name: SWAP_RATE
        description: "{{ doc('col_swap_rate') }}"
        data_type: varchar

  - name: omni_swap_rate
    description: "Downstream reporting table for swap rates."
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [END_MONTH]
    columns:
      - name: END_MONTH
        description: "{{ doc('col_end_month') }}"
        data_type: varchar
        tests:
          - unique
          - not_null
      - name: SWAP_RATE
        description: "{{ doc('col_swap_rate') }}"
        data_type: varchar
